# Created with package:mono_repo v2.1.0
language: dart

# Custom configuration
branches:
  exclude: []

jobs:
  include:
    - stage: analyze
      name: "SDK: stable; PKGS: canonical_json, chunked_stream, http_methods, neat_periodic_task, pem, retry, sanitize_html, shelf_router, shelf_router_generator, slugid; TASKS: `dartanalyzer .`"
      dart: stable
      env: PKGS="canonical_json chunked_stream http_methods neat_periodic_task pem retry sanitize_html shelf_router shelf_router_generator slugid"
      script: ./tool/travis.sh dartanalyzer
    - stage: analyze
      name: "SDK: stable; PKGS: canonical_json, chunked_stream, http_methods, neat_periodic_task, pem, retry, sanitize_html, shelf_router, shelf_router_generator, slugid; TASKS: `dartfmt -n --set-exit-if-changed .`"
      dart: stable
      env: PKGS="canonical_json chunked_stream http_methods neat_periodic_task pem retry sanitize_html shelf_router shelf_router_generator slugid"
      script: ./tool/travis.sh dartfmt
    - stage: unit_test
      name: "SDK: stable; PKGS: canonical_json, chunked_stream, http_methods, neat_periodic_task, pem, retry, sanitize_html, shelf_router, shelf_router_generator, slugid; TASKS: `pub run test`"
      dart: stable
      env: PKGS="canonical_json chunked_stream http_methods neat_periodic_task pem retry sanitize_html shelf_router shelf_router_generator slugid"
      script: ./tool/travis.sh test

stages:
  - analyze
  - unit_test

cache:
  directories:
    - "$HOME/.pub-cache"
