name: dart_neats
# This should never be published it just locks the dev_dependencies for
# repository management, so they don't have to be installed globally.
publish_to: none
dev_dependencies:
  mono_repo: ^1.2.1
  pubspec_parse: ^0.1.4
